Repository SWM-15th-ForU/freebe-frontend, pull requests merged in 2024-09, with the labels that each got.

#15 [FU-155] client side token management
  src/app/[id]/products/[product]/page.tsx
  src/app/auth/route.ts
  src/app/login/error/page.tsx
  src/app/login/page.tsx
  src/app/login/redirect/route.ts
  src/app/photographer/page.tsx
  src/components/buttons/login-button.tsx
  src/containers/customer/products/info.tsx
  src/containers/customer/products/products.css.ts
  src/containers/main/header.tsx
  src/services/client/core/index.ts
  src/services/client/core/interceptor.ts
  src/services/client/customer/reservation.ts
  src/services/client/photographer/products.ts
  src/services/common/interceptor.ts
  src/services/server/core/auth.ts
  src/services/server/core/index.ts
  src/services/server/core/interceptor.ts
  src/services/server/login.ts
  src/utils/type-guards.ts
Labels: ✨ Feature, 📬 API

#20 [FU-120] photographer reservation list
  public/icons/calender-blue.svg
  public/icons/calender.svg
  public/icons/down-grey.svg
  public/icons/filter-blue.svg
  public/icons/filter.svg
  public/icons/list-blue.svg
  public/icons/list.svg
  public/icons/plus.svg
  public/icons/reservation/created.svg
  public/icons/reservation/person.svg
  public/icons/right.svg
  public/icons/search.svg
  src/app/photographer/layout.tsx
  src/app/photographer/page.tsx
  src/app/root.css.ts
  src/components/agreement/agreement.css.ts
  src/components/buttons/buttons.css.ts
  src/components/buttons/common-buttons.tsx
  src/components/common/common.css.ts
  src/components/common/filter.tsx
  src/components/common/search.tsx
  src/components/common/slider.tsx
  src/components/inputs/input.css.ts
  src/constants/common/reservation.ts
  src/constants/photographer/mypage.ts
  src/containers/customer/products/info/info.css.ts
  src/containers/customer/products/list/list.css.ts
  src/containers/customer/products/products.css.ts
  src/containers/customer/reservation/reference/selected.tsx
  src/containers/customer/reservation/submit/parts/parts.css.ts
  src/containers/customer/reservation/submit/submit.css.ts
  src/containers/photographer/list/card.tsx
  src/containers/photographer/list/content.tsx
  src/containers/photographer/list/index.tsx
  src/containers/photographer/list/list.css.ts
  src/containers/photographer/list/status-list.tsx
  src/containers/photographer/login/login.css.ts
  src/containers/photographer/main/controller.tsx
  src/containers/photographer/main/header/header.css.ts
  src/containers/photographer/main/header/profile-menu.tsx
  src/containers/photographer/main/header/profile.tsx
  src/containers/photographer/main/index.tsx
  src/containers/photographer/main/main.css.ts
  src/containers/photographer/mypage/mypage.css.ts
  src/containers/photographer/mypage/navbar.tsx
  src/containers/photographer/product/product.css.ts
  src/services/client/photographer/products.ts
  src/services/client/photographer/reservations.ts
  src/styles/breakpoints.css.ts
  src/styles/colors.css.ts
  src/styles/globals.css
  src/styles/sprinkles.css.ts
  src/styles/text.css.ts
  src/types/reservation-types.d.ts
  src/types/service-types.d.ts
  src/utils/date.ts
Labels: ✨ Feature, 🎨 Publish, 📬 API

#16 [FU-157] form validation
  package-lock.json
  package.json
  src/app/globals.css
  src/app/layout.tsx
  src/app/login/[roleType]/register/page.tsx
  src/app/photographer/new-product/page.tsx
  src/components/buttons/buttons.css.ts
  src/components/buttons/common-buttons.tsx
  src/containers/customer/products/info/product-discount.tsx
  src/containers/customer/reservation/reservation-form-provider.tsx
  src/containers/customer/reservation/submit-form.tsx
  src/containers/photographer/product/form/discount-field-array.tsx
  src/containers/photographer/product/form/discount-input.tsx
  src/containers/photographer/product/form/item-field-array.tsx
  src/containers/photographer/product/form/item-input.tsx
  src/containers/photographer/product/form/option-field-array.tsx
  src/containers/photographer/product/form/option-input.tsx
  src/containers/photographer/product/product-form.tsx
  src/containers/photographer/product/product.css.ts
  src/services/client/photographer/products.ts
  src/types/form-types.d.ts
  src/types/product-types.d.ts
  src/utils/apis/core.ts
  src/utils/apis/login.ts
  src/utils/apis/products.ts
Labels: ✨ Feature, 🎨 Publish

#21 [FU-114] reservation details page
  public/icons/edit-blue.svg
  public/icons/full-size.svg
  public/icons/options.svg
  public/icons/right-white.svg
  src/app/login/error/page.tsx
  src/app/photographer/reservation/[reservationId]/page.tsx
  src/app/root.css.ts
  src/components/buttons/buttons.css.ts
  src/components/buttons/common-buttons.tsx
  src/components/common/addition-info.tsx
  src/components/common/chip.tsx
  src/components/common/common.css.ts
  src/components/images/full-image.tsx
  src/components/images/image-thumbnail.tsx
  src/components/images/images.css.ts
  src/components/inputs/input.css.ts
  src/components/inputs/text-input.tsx
  src/constants/common/reservation.ts
  src/containers/photographer/list/card.tsx
  src/containers/photographer/list/index.tsx
  src/containers/photographer/list/status-list.tsx
  src/containers/photographer/product/form/image-input.tsx
  src/containers/photographer/reservation/index.tsx
  src/containers/photographer/reservation/reservation.css.ts
  src/containers/photographer/reservation/section/control/cancel-modal.tsx
  src/containers/photographer/reservation/section/control/confirm.tsx
  src/containers/photographer/reservation/section/control/control.css.ts
  src/containers/photographer/reservation/section/control/index.tsx
  src/containers/photographer/reservation/section/control/memo.tsx
  src/containers/photographer/reservation/section/control/status-modal.tsx
  src/containers/photographer/reservation/section/details/customer-details.tsx
  src/containers/photographer/reservation/section/details/image-details.tsx
  src/containers/photographer/reservation/section/details/index.tsx
  src/containers/photographer/reservation/section/details/photo-details.tsx
  src/containers/photographer/reservation/section/details/request-details.tsx
  src/containers/photographer/reservation/section/details/schedule-details.tsx
  src/containers/photographer/reservation/section/fields/field.tsx
  src/containers/photographer/reservation/section/fields/option-field.tsx
  src/containers/photographer/reservation/section/fields/schedule-field.tsx
  src/containers/photographer/reservation/section/section-layout.tsx
  src/containers/photographer/reservation/section/section.css.ts
  src/containers/photographer/reservation/status/icon.tsx
  src/containers/photographer/reservation/status/index.tsx
  src/containers/photographer/reservation/status/progress.tsx
  src/containers/photographer/reservation/status/status.css.ts
  src/containers/photographer/reservation/title.tsx
  src/services/client/photographer/reservations.ts
  src/services/server/login.ts
  src/services/server/photographer/reservation.ts
  src/styles/colors.css.ts
  src/types/reservation-types.d.ts
  src/utils/parse.ts
  src/utils/reservation.ts
  src/utils/type-guards.ts
Labels: ✨ Feature, 🎨 Publish, 📬 API

#24 [FU-200] handle logout
  src/app/auth/route.ts
  src/components/common/common.css.ts
  src/containers/photographer/main/header/header.css.ts
  src/containers/photographer/main/header/profile-menu.tsx
  src/containers/photographer/main/header/url.tsx
  src/services/client/core/auth.ts
  src/services/server/core/auth.ts
  src/services/server/login.ts
Labels: ✨ Feature, 🎨 Publish, 📬 API

#22 [FU-184] view profile at customer side
  public/icons/profile.svg
  src/app/[id]/customer.css.ts
  src/app/[id]/layout.tsx
  src/app/[id]/page.tsx
  src/app/[id]/products/layout.tsx
  src/app/layout.tsx
  src/components/buttons/buttons.css.ts
  src/components/buttons/common-buttons.tsx
  src/components/common/bottom-sheet.tsx
  src/components/common/common.css.ts
  src/components/common/profile.tsx
  src/components/customer/customer.css.ts
  src/components/customer/service-footer.tsx
  src/containers/customer/main/background-image.tsx
  src/containers/customer/main/info-sheet.tsx
  src/containers/customer/main/main.css.ts
  src/services/client/photographer/reservations.ts
  src/services/server/core/index.ts
  src/services/server/customer/photographer.ts
  src/styles/text.css.ts
  src/types/profile-types.d.ts
Labels: ✨ Feature, 🎨 Publish, 📬 API

#25 [FU-185] edit photographer profile
  .github/workflows/ci_workflow_dev.yml
  src/app/[id]/products/[product]/reservation/submit/@modal/(.)agreement/page.tsx
  src/app/[id]/products/[product]/reservation/submit/agreement/page.tsx
  src/app/photographer/layout.tsx
  src/app/photographer/mypage/faqs/page.tsx
  src/app/photographer/mypage/layout.tsx
  src/app/photographer/mypage/mypage.css.ts
  src/app/photographer/mypage/previous/page.tsx
  src/app/photographer/mypage/products/page.tsx
  src/app/photographer/mypage/profile/page.tsx
  src/app/photographer/mypage/schedule/page.tsx
  src/components/buttons/buttons.css.ts
  src/components/buttons/common-buttons.tsx
  src/components/common/bottom-sheet.tsx
  src/components/common/common.css.ts
  src/components/common/dropdown.tsx
  src/components/images/images.css.ts
  src/components/images/profile-image.tsx
  src/components/inputs/input.css.ts
  src/containers/customer/main/background-image.tsx
  src/containers/customer/main/info-sheet.tsx
  src/containers/customer/main/main.css.ts
  src/containers/customer/reservation/submit/parts/parts.css.ts
  src/containers/customer/reservation/submit/parts/select-option-form.tsx
  src/containers/photographer/main/header/profile.tsx
  src/containers/photographer/main/index.tsx
  src/containers/photographer/mypage/mypage.css.ts
  src/containers/photographer/mypage/navbar.tsx
  src/containers/photographer/mypage/profile/edit/banner.tsx
  src/containers/photographer/mypage/profile/edit/basic-info.tsx
  src/containers/photographer/mypage/profile/edit/edit.css.ts
  src/containers/photographer/mypage/profile/edit/index.tsx
  src/containers/photographer/mypage/profile/edit/links.tsx
  src/containers/photographer/mypage/profile/index.tsx
  src/containers/photographer/mypage/profile/preview.tsx
  src/containers/photographer/mypage/profile/profile.css.ts
  src/containers/photographer/mypage/profile/submit.tsx
  src/containers/photographer/product/form/discount-field-array.tsx
  src/containers/photographer/product/form/image-input.tsx
  src/containers/photographer/product/form/item-field-array.tsx
  src/containers/photographer/product/form/option-field-array.tsx
  src/containers/photographer/product/product-form.tsx
  src/containers/photographer/product/product.css.ts
  src/containers/ui/mypage-layout.tsx
  src/containers/ui/preparing.tsx
  src/containers/ui/ui.css.ts
  src/services/client/photographer/mypage/profile.ts
  src/services/server/photographer/mypage/profile.ts
  src/types/profile-types.d.ts
Labels: ✨ Feature, 🎨 Publish, 📬 API

#23 [FU-117] view reservation
  src/app/customer/reservation/[reservationId]/page.tsx
  src/components/common/chip.tsx
  src/components/common/common.css.ts
  src/components/common/filter.tsx
  src/components/common/toast.ts
  src/containers/common/status/icon.tsx
  src/containers/common/status/index.tsx
  src/containers/common/status/progress.tsx
  src/containers/common/status/status.css.ts
  src/containers/customer/products/info/product-discount.tsx
  src/containers/customer/products/info/product-option.tsx
  src/containers/customer/reservation/details/detail.css.ts
  src/containers/customer/reservation/details/info.tsx
  src/containers/customer/reservation/details/infos/confirm.tsx
  src/containers/customer/reservation/details/infos/infos.css.ts
  src/containers/customer/reservation/details/infos/option.tsx
  src/containers/customer/reservation/details/infos/product.tsx
  src/containers/customer/reservation/details/infos/request.tsx
  src/containers/customer/reservation/details/infos/schedule.tsx
  src/containers/customer/reservation/details/status.tsx
  src/containers/customer/reservation/reservation-details.tsx
  src/containers/customer/reservation/reservation.css.ts
  src/containers/customer/reservation/submit-form.tsx
  src/containers/customer/reservation/submit/parts/option-controller.tsx
  src/containers/customer/reservation/submit/parts/select-option-form.tsx
  src/containers/customer/reservation/submit/parts/total-price-form.tsx
  src/containers/photographer/main/header/url.tsx
  src/containers/photographer/product/product-form.tsx
  src/containers/photographer/reservation/index.tsx
  src/containers/photographer/reservation/section/control/confirm.tsx
  src/containers/photographer/reservation/status/index.tsx
  src/containers/photographer/reservation/status/progress.tsx
  src/containers/ui/product-header-layout.tsx
  src/services/server/customer/reservation.ts
  src/services/server/photographer/reservation.ts
  src/types/reservation-types.d.ts
  src/utils/parse.ts
  src/utils/reservation.ts
Labels: ✨ Feature, 🎨 Publish, 📬 API

#26 [FU-178] photographer signup
  package-lock.json
  package.json
  src/app/photographer/join/page.tsx
  src/containers/photographer/join/agreements.tsx
  src/containers/photographer/join/index.tsx
  src/containers/photographer/join/join.css.ts
  src/containers/photographer/join/profile.tsx
  src/containers/photographer/main/header.tsx
  src/containers/photographer/main/header/header.css.ts
  src/services/client/photographer/profile.ts
  src/types/profile-types.d.ts
Labels: ✨ Feature, 🎨 Publish, 📬 API

#32 [FU-234] keep userdata after login
  package-lock.json
  src/app/photographer/page.tsx
  src/components/buttons/login-button.tsx
  src/containers/photographer/main/header.tsx
  src/hooks/useUserInfo.ts
  src/services/client/core/auth.ts
  src/services/server/core/auth.ts
Labels: 🐞 BugFix

#30 [FU-235] 서버 배포 자동화
  .github/workflows/cd_workflow_dev.yml
  appspec.yml
  scripts/start.sh
  scripts/stop.sh
Labels: 🌏 Deploy

#33 [FU-255] replace photographerId with profileName
  .github/workflows/cd_workflow_dev.yml
  src/app/(customer)/[profileName]/main.css.ts
  src/app/(customer)/[profileName]/page.tsx
  src/app/(customer)/[profileName]/products/[productId]/page.tsx
  src/app/(customer)/[profileName]/products/[productId]/reservation/layout.tsx
  src/app/(customer)/[profileName]/products/[productId]/reservation/reference/page.tsx
  src/app/(customer)/[profileName]/products/[productId]/reservation/submit/@modal/(.)schedule/page.tsx
  src/app/(customer)/[profileName]/products/[productId]/reservation/submit/@modal/default.tsx
  src/app/(customer)/[profileName]/products/[productId]/reservation/submit/layout.tsx
  src/app/(customer)/[profileName]/products/[productId]/reservation/submit/page.tsx
  src/app/(customer)/[profileName]/products/[productId]/reservation/submit/schedule/page.tsx
  src/app/(customer)/[profileName]/products/page.tsx
  src/app/(customer)/customer/reservation/[formId]/page.tsx
  src/app/photographer/reservation/[formId]/page.tsx
  src/components/buttons/login-button.tsx
  src/containers/customer/main/info-sheet.tsx
  src/containers/customer/products/info.tsx
  src/containers/customer/reservation/details/cancel-modal.tsx
  src/containers/customer/reservation/reservation-form-provider.tsx
  src/containers/customer/reservation/submit-form.tsx
  src/containers/customer/reservation/submit/parts/customer-info-form.tsx
  src/containers/photographer/join/index.tsx
  src/containers/photographer/join/profile.tsx
  src/containers/photographer/main/header.tsx
  src/containers/photographer/mypage/profile/edit/basic-info.tsx
  src/containers/photographer/mypage/profile/index.tsx
  src/containers/photographer/mypage/profile/preview.tsx
  src/containers/photographer/reservation/section/control/cancel-modal.tsx
  src/containers/photographer/reservation/section/control/status-modal.tsx
  src/services/client/core/auth.ts
  src/services/client/customer/reservation.ts
  src/services/client/photographer/mypage/profile.ts
  src/services/client/photographer/profile.ts
  src/services/server/customer/photographer.ts
  src/services/server/customer/product.ts
  src/services/server/customer/reservation.ts
  src/services/server/photographer/mypage/profile.ts
  src/services/server/photographer/reservation.ts
  src/types/profile-types.d.ts
  src/types/route-parameters.d.ts
Labels: 📬 API

#34 [FU-258] 배포 자동화 스크립트 버그 픽스
  .github/workflows/cd_workflow_dev.yml
  appspec.yml
  scripts/start.sh
  scripts/stop.sh
Labels: 🐞 BugFix

#39 [FU-221] Google Analytics
  package-lock.json
  package.json
  src/app/layout.tsx
Labels: 🌏 Deploy

#36 [FU-225] set metadata
  public/favicon.ico
  public/favicon/favicon.ico
  public/images/opengraph.png
  src/app/(customer)/[profileName]/page.tsx
  src/app/(customer)/layout.tsx
  src/app/layout.tsx
  src/constants/metadata.ts
Labels: 🎨 Publish
